name: 'Cleanup Workflow History'
description: 'A reusable GitHub Action to delete old workflow runs based on age.'

inputs:
  days_old:
    description: 'Number of days to keep workflow runs'
    required: false
    default: 7
  per_page:
    description: 'Number of workflow runs to fetch per request'
    required: false
    default: 50

runs:
  using: 'composite'
  steps:
    - name: Delete old workflow runs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        # Calculate cutoff date based on days_old
        CUTOFF_DATE=$(date -u -d "-${{ inputs.days_old }} days" +%Y-%m-%dT%H:%M:%SZ)

        # Use gh CLI to list and delete old workflow runs in one go
        gh run list \
          --limit ${{ inputs.per_page }} \
          --json databaseId,name,createdAt \
          --jq ".[] | select(.createdAt < \"$CUTOFF_DATE\") | .databaseId" | \
        while read -r ID; do
          echo "Deleting workflow run ID=$ID"
          gh run delete "$ID" && echo "Successfully deleted ID=$ID" || echo "Failed to delete ID=$ID"
        done
