name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.0

      - name: setup test infrastructure
        run: docker compose -f test/compose.yml up -d

      - name: install dependencies
        run: go mod tidy
      
      - name: build
        run: go build ./...

      - name: test
        run: go test -timeout 120s ./... -v -coverprofile=coverage.out

      - name: workflow cleanup
        uses: fgrzl/workflow-cleanup@v1